definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  errcode.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  model.Tag:
    properties:
      created_by:
        type: string
      created_on:
        description: 创建时间
        type: integer
      deleted_on:
        description: 删除时间
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        description: 更新时间
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
  model.TagSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
        type: object
    type: object
  service.CreateTagRequest:
    properties:
      created_by:
        description: 创建者
        type: string
      name:
        description: 标签名称
        type: string
      state:
        description: 状态，是否启用(0 为禁用、1 为启用)
        type: integer
    required:
    - created_by
    - name
    type: object
  service.UpdateTagRequest:
    properties:
      id:
        description: 标签id
        type: integer
      modifiedBy:
        description: 修改者
        type: string
      name:
        description: 标签名称
        type: string
      state:
        description: 状态，是否启用(0 为禁用、1 为启用)
        type: integer
    required:
    - id
    - modifiedBy
    type: object
info:
  contact: {}
  description: Go 语言编程之旅：一起用 Go 做项目
  license: {}
  termsOfService: https://github.com/golang-minibear2333/gin-blog
  title: 博客系统
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态，是否启用(0 为禁用、1 为启用)
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个标签
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Tag'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 新增标签
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: 标签 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 删除标签
    put:
      consumes:
      - application/json
      parameters:
      - description: 标签 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 请求体
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/service.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Tag'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 更新标签
swagger: "2.0"
